package org.app.model;

public enum Victoire {

    SUBMISSION_COMBATTANT_1,
    POINT_COMBATTANT_1,
    DISQUALIFICATION_COMBATTANT_1,
    ABANDON_COMBATTANT_1,

    SUBMISSION_COMBATTANT_2,
    POINT_COMBATTANT_2,
    DISQUALIFICATION_COMBATTANT_2,
    ABANDON_COMBATTANT_2,
    MATCH_NULL
}
